# Generated by Django 3.0.3 on 2020-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='picture',
            field=models.ImageField(blank=True, default='Avatar.png', null=True, upload_to='users/'),
        ),
    ]
